#!/bin/sh

set -e

# Encoding

for i in $(seq 1 100); do
    str="$(head -n5 /dev/random | md5sum)"
    str="$(printf "%s" "$str")"
    echo "Test #$i: b64_encode('$str')"
    # shellcheck disable=SC2006
    out=`./test_base64_bin e "$str"`
    expected="$(printf "%s" "$str" | base64 -w 0)"

    if [ "$out" != "$expected" ]; then
        echo "Test failed: '$out' != '$expected'" >&2
        exit 1
    fi
done

# Decoding

for i in $(seq 1 100); do
    str="$(head -n5 /dev/random | md5sum)"
    input="$(printf "%s" "$str" | base64 -w 0)"
    echo "Test #$i: b64_decode('$input')"
    # shellcheck disable=SC2006
    out=`./test_base64_bin d "$input"`

    if [ "$out" != "$str" ]; then
        echo "Test failed: '$out' != '$str'" >&2
        exit 1
    fi
done

# Both

for i in $(seq 1 100); do
    str="$(head -n5 /dev/random | md5sum)"
    echo "Test #$i: b64_decode(b64_encode('$input'))"
    
    encoded="$(./test_base64_bin e "$str")"
    decoded="$(./test_base64_bin d "$encoded")"

    if [ "$decoded" != "$str" ]; then
        echo "Test failed: '$decoded' != '$str'" >&2
        exit 1
    fi
done