name: Build

on: [push, pull_request]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y xxd valgrind apache2-utils

      - name: Build
        run: |
          make clean all

      - name: Test
        run: |
          make check

      - name: Valgrind
        run: |
          make check-valgrind

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            bin/
            tests/freehttpd.log
            tests/valgrind.log
            tests/vgcore.*
