name: Build

on: [push, pull_request]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y xxd valgrind apache2-utils gcc-14 build-essential
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 500
          gcc --version

      - name: Build
        run: |
          ./bootstrap
          ./configure CC=/usr/bin/gcc-14 --prefix=$(pwd)/build --disable-silent-rules
          make -j$(nproc)
          make install

      - name: Test
        run: |
          make distcheck

      - name: Benchmark
        run: |
          make check-benchmark || (cat tests/freehttpd.log && exit 1)

      - name: Valgrind Benchmark
        run: |
          make check-valgrind-benchmark || (cat tests/freehttpd-valgrind.log && exit 1)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
            tests/freehttpd-valgrind.log
            tests/freehttpd.log
            tests/valgrind.log
            tests/vgcore.*
