name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xxd valgrind apache2-utils

      - name: Build
        run: |
          make clean all

      - name: Test
        run: |
          make check

      - name: Valgrind
        run: |
          make check-valgrind